### ISSUE TITLE
[Bug]: 关于MQTT能连接成功但是不能正常工作的问题

### ISSUE THREAD

**Issue by KleinerSource** [pppscn/SmsForwarder#310]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

请问mqtt应该如何配置? 我配置好了测试的时候 显示 请求失败: MQTT连接成功
服务器那边收到的信息只有 {"terminal_uid":"客户端id"} 而且只生成了 输入消息主题 没有输出消息主题

之前的issues closed了 打不开了 所以只能重发一份 
这次附上日志了.

### 复现步骤

输入mqtt账号密码
填入了输入消息主题和输出消息主题 还有客户端ID

### 是否必现

是（Yes）

### 出现问题的手机信息

MI5S  雷电模拟器

### 出现问题的安卓版本、系统版本

MIUI10  Android9

### 提供报错堆栈【请提供logcat抓取的日志，参考： https://blog.csdn.net/m0_64776928/article/details/126005119 】

错误日志内容为
06-12 09:19:01.330 2676 2676 W MessengerIpcClient: Received response for unknown request: 1
06-12 09:19:10.871 3475 3518 D EGL_adreno: eglMakeCurrent: 0x7fff6a364d80: ver 3 0 (tinfo 0x7fff6a215f80)
06-12 09:19:10.920 1407 3226 D audio_hw_hal: raw_start_output_stream, stream=0xf671b000, sampleRate=48000, channel=2, bps=16, bufSize=4096
06-12 09:19:10.922 3475 3632 D SocketFragment: SocketSetting(method=MQTT, address=10.0.0.51, port=1883, msgTemplate=, secret=, username=ksmqtt, password=Ks123333, inCharset=UTF-8, outCharset=UTF-8, inMessageTopic=smsf/state, outMessageTopic=smsf/cmd, uriType=, path=, clientId=smstest)
06-12 09:19:10.925 3475 3633 V MQTT : 开始进行连掿{uri: 'tcp://10.0.0.51:1883', username: 'ksmqtt', password: 'Ks123333'}
06-12 09:19:10.937 3475 3475 I [LiveEventBus]: post: finish with key: key_sender_test
06-12 09:19:10.937 3475 3475 I [LiveEventBus]: message received: finish
06-12 09:19:11.407 3475 3633 V MQTT : 连接成功 {uri: 'tcp://10.0.0.51:1883', username: 'ksmqtt', password: 'Ks123333'}
06-12 09:19:11.409 3475 3633 W System.err: java.lang.Exception: Toast callstack! strTip=
06-12 09:19:11.409 3475 3633 W System.err: at android.widget.Toast.show(Toast.java:143)
06-12 09:19:11.409 3475 3633 W System.err: at com.idormy.sms.forwarder.utils.XToastUtils$Companion.b(Unknown Source:13)
06-12 09:19:11.409 3475 3633 W System.err: at com.idormy.sms.forwarder.utils.SendUtils.f(SendUtils.kt:14)
06-12 09:19:11.409 3475 3633 W System.err: at com.idormy.sms.forwarder.utils.sender.SocketUtils$Companion$sendMsg$2$1.invoke(SocketUtils.kt:2)
06-12 09:19:11.409 3475 3633 W System.err: at com.idormy.sms.forwarder.utils.sender.SocketUtils$Companion$sendMsg$2$1.invoke(SocketUtils.kt:1)
06-12 09:19:11.409 3475 3633 W System.err: at com.gitee.xuankaicat.kmnkt.socket.OnOpenCallback.success(OnOpenCallback.kt:2)
06-12 09:19:11.409 3475 3633 W System.err: at com.gitee.xuankaicat.kmnkt.socket.MQTT.doClientConnection(MQTT.kt:5)
06-12 09:19:11.409 3475 3633 W System.err: at com.gitee.xuankaicat.kmnkt.socket.MQTT.access$doClientConnection(Unknown Source:0)
06-12 09:19:11.409 3475 3633 W System.err: at com.gitee.xuankaicat.kmnkt.socket.MQTT$open$1.invoke(MQTT.kt:21)
06-12 09:19:11.409 3475 3633 W System.err: at com.gitee.xuankaicat.kmnkt.socket.MQTT$open$1.invoke(MQTT.kt:1)
06-12 09:19:11.409 3475 3633 W System.err: at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Unknown Source:2)
06-12 09:19:11.413 1574 1588 E memtrack: Couldn't load memtrack module
06-12 09:19:11.413 1574 1588 W android.os.Debug: failed to get memory consumption info: -1
06-12 09:19:11.450 1574 1588 E memtrack: Couldn't load memtrack module
06-12 09:19:11.450 1574 1588 W android.os.Debug: failed to get memory consumption info: -1
06-12 09:19:11.459 3475 3518 E EGL_adreno: tid 3518: eglSurfaceAttrib(1338): error 0x3009 (EGL_BAD_MATCH)
06-12 09:19:11.459 3475 3518 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7fff506e7c00, error=EGL_BAD_MATCH
06-12 09:19:11.465 3475 3518 D EGL_adreno: eglMakeCurrent: 0x7fff6a364d80: ver 3 0 (tinfo 0x7fff6a215f80)
06-12 09:19:11.468 1574 1588 E memtrack: Couldn't load memtrack module
06-12 09:19:11.468 1574 1588 W android.os.Debug: failed to get memory consumption info: -1
06-12 09:19:11.478 1574 1588 E memtrack: Couldn't load memtrack module
06-12 09:19:11.478 1574 1588 W android.os.Debug: failed to get memory consumption info: -1
06-12 09:19:11.487 1574 1588 E memtrack: Couldn't load memtrack module
06-12 09:19:11.487 1574 1588 W android.os.Debug: failed to get memory consumption info: -1
06-12 09:19:12.122 1460 1511 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0

**Comment by pppscn** [comment]
你的mqtt服务端怎么实现的，提供一下代码，我去调试一下

**Comment by pppscn** [comment]
参考这篇文章搭建的本机mqtt服务：
https://blog.csdn.net/quan278905570/article/details/119303039

**测试结果如下：**

```
2023-07-07 13:54:19.576 10272-12275 SocketFragment          com.idormy.sms.forwarder             D  SocketSetting(method=MQTT, address=10.8.11.47, port=1883, msgTemplate=, secret=, username=ksmqtt, password=Ks123333, inCharset=UTF-8, outCharset=UTF-8, inMessageTopic=smsf, outMessageTopic=smsf, uriType=, path=, clientId=)
2023-07-07 13:54:19.581 10272-12276 MQTT                    com.idormy.sms.forwarder             V  开始进行连接 {uri: 'tcp://10.8.11.47:1883', username: 'ksmqtt', password: 'Ks123333'}
2023-07-07 13:54:19.584 10272-12277 TrafficStats            com.idormy.sms.forwarder             D  tagSocket(131) with statsTag=0xffffffff, statsUid=-1
2023-07-07 13:54:19.592 10272-10272 [LiveEventBus]          com.idormy.sms.forwarder             I  post: finish with key: key_sender_test
2023-07-07 13:54:19.592 10272-10272 [LiveEventBus]          com.idormy.sms.forwarder             I  message received: finish
2023-07-07 13:54:19.893 10272-12276 MQTT                    com.idormy.sms.forwarder             V  连接成功 {uri: 'tcp://10.8.11.47:1883', username: 'ksmqtt', password: 'Ks123333'}
2023-07-07 13:54:19.894 10272-12276 SocketUtils             com.idormy.sms.forwarder             D  MQTT连接成功
2023-07-07 13:54:19.894 10272-12276 MQTT                    com.idormy.sms.forwarder             V  开始订阅smsf
2023-07-07 13:54:19.910 10272-12276 MQTT                    com.idormy.sms.forwarder             V  发送消息 {uri: 'tcp://10.8.11.47:1883', topic: 'smsf', message: '{"msg": "19999999999\n【测试通道】恭喜您，该发送通道测试成功，请继续添加转发规则！\nSIM1_测试运营商_18888888888\nSubId：0\n2023-07-07 05:54:19\nsdk_gphone_x86_64"}'}
2023-07-07 13:54:19.912 10272-12280 MQTT                    com.idormy.sms.forwarder             V  收到来自[smsf]的消息"{"msg": "19999999999\n【测试通道】恭喜您，该发送通道测试成功，请继续添加转发规则！\nSIM1_测试运营商_18888888888\nSubId：0\n2023-07-07 05:54:19\nsdk_gphone_x86_64"}"
```
![微信截图_20230707135628](https://github.com/pppscn/SmsForwarder/assets/5105854/223d4793-2191-465e-b89b-3c8213ebc692)


**请重新下载每周构建版测试**

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
