### ISSUE TITLE
[Suggestion]: 添加iCloud邮箱支持

### ISSUE THREAD

**Issue by Hydro3ia** [pppscn/SmsForwarder#541]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

请添加对Icloud邮箱的支持

**Comment by pppscn** [comment]
目前尝试失败，连不上 smtp 服务器

```
2024-11-14 22:42:07.607 13766-13812 System.err              com.idormy.sms.forwarder             W  javax.mail.MessagingException: Could not connect to SMTP host: smtp.mail.me.com, port: 587;
2024-11-14 22:42:07.607 13766-13812 System.err              com.idormy.sms.forwarder             W    nested exception is:
2024-11-14 22:42:07.607 13766-13812 System.err              com.idormy.sms.forwarder             W  	javax.net.ssl.SSLException: Unable to parse TLS packet header
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2212)
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at javax.mail.Service.connect(Service.java:364)
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at javax.mail.Service.connect(Service.java:222)
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at javax.mail.Service.connect(Service.java:171)
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at javax.mail.Transport.send0(Transport.java:230)
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at javax.mail.Transport.send(Transport.java:100)
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.idormy.sms.forwarder.utils.mail.SmimeUtils$sendPlainEmail$2.invokeSuspend(SmimeUtils.kt:70)
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.idormy.sms.forwarder.utils.mail.SmimeUtils$sendPlainEmail$2.invoke(Unknown Source:8)
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.idormy.sms.forwarder.utils.mail.SmimeUtils$sendPlainEmail$2.invoke(Unknown Source:4)
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
2024-11-14 22:42:07.608 13766-13812 System.err              com.idormy.sms.forwarder             W  	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
2024-11-14 22:42:07.609 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.idormy.sms.forwarder.utils.mail.SmimeUtils.sendPlainEmail(SmimeUtils.kt:66)
2024-11-14 22:42:07.609 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.idormy.sms.forwarder.utils.mail.EmailSender.sendEmail(EmailSender.kt:159)
2024-11-14 22:42:07.609 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.idormy.sms.forwarder.utils.sender.EmailUtils$Companion$sendMsg$1$job$1.invokeSuspend(EmailUtils.kt:340)
2024-11-14 22:42:07.609 13766-13812 System.err              com.idormy.sms.forwarder             W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-11-14 22:42:07.609 13766-13812 System.err              com.idormy.sms.forwarder             W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-11-14 22:42:07.609 13766-13812 System.err              com.idormy.sms.forwarder             W  	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2024-11-14 22:42:07.609 13766-13812 System.err              com.idormy.sms.forwarder             W  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2024-11-14 22:42:07.609 13766-13812 System.err              com.idormy.sms.forwarder             W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-11-14 22:42:07.609 13766-13812 System.err              com.idormy.sms.forwarder             W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-11-14 22:42:07.609 13766-13812 System.err              com.idormy.sms.forwarder             W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-11-14 22:42:07.609 13766-13812 System.err              com.idormy.sms.forwarder             W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  Caused by: javax.net.ssl.SSLException: Unable to parse TLS packet header
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:807)
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602)
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:376)
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160)
2024-11-14 22:42:07.610 13766-13812 System.err              com.idormy.sms.forwarder             W  	... 23 more
```


**参考资料**

1、[生成一个 App 专用密码](https://support.apple.com/zh-cn/102654)

2、（可选，直接下拉框选 `@icloud.com` 即可）[适用于 iCloud 邮件发件服务器的 SMTP 信息](https://support.apple.com/zh-cn/102525)

**Comment by pppscn** [comment]
已经添加，覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
